import { Board } from "@/components/Board/board";

import { Game } from "@/components/Game/game";
import { Square } from "@/components/Square/square";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <div className={poppins.className}>
      <Board>
        <Game />
      </Board>
    </div>
  );
}
